sudo: required
services:
    - docker

before_install:
    - docker build -t pointslead/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true pointslead/react-test npm test -- --coverage

after_success:
    - docker build -t hayrettinm/multi-client ./client
    - docker build -t hayrettinm/multi-nginx ./nginx
    - docker build -t hayrettinm/multi-server ./server
    - docker build -t hayrettinm/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push hayrettinm/multi-client
    - docker push hayrettinm/multi-nginx
    - docker push hayrettinm/multi-server
    - docker push hayrettinm/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-container
    env: MultiContainer-env
    bucket_name: elasticbeanstalk-eu-west-2-182422531796
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY