sudo: required
services:
    - docker

before_install:
    - docker build -t pointslead/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true pointslead/react-test npm test -- --coverage

after_success:
    - docker build -t pointslead/multi-client ./client
    - docker build -t pointslead/multi-nginx ./nginx
    - docker build -t pointslead/multi-server ./server
    - docker build -t pointslead/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push pointslead/multi-client
    - docker push pointslead/multi-nginx
    - docker push pointslead/multi-server
    - docker push pointslead/multi-worker
